version: 2
stages:
  build:
    machine: true
    working_directory: /home/circleci/go/src/github.com/drud/ghlabel


    environment:
      GOPATH: /home/circleci/go
      ARTIFACTS: /artifacts

    steps:
      - run: mkdir -p ~/go/src/github.com/drud/ghlabel && mkdir -p ~/go/lib && mkdir -p ~/go/bin

      - checkout

      - run:
          command: sh ./.circleci/generate_artifacts.sh $ARTIFACTS
          name: tar/zip up artifacts and make hashes

      - run: make staticcheck
      - run: make test

      - store_artifacts:
          path: /artifacts
          name: Artifact storage